config/routes.rb
Rails.application.routes.draw do

  resources :stories
  resources :likes, only: [:create,:destroy]

  resources :comments
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }

  resources :users, only: [:show]

  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"

  get 'search', to:"users#search"
  get 'home/about'
  get 'posts/myposts'
  get 'stories/mystories'

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         followability

has_many :posts
has_many :comments
has_many :stories
has_one_attached :avatar
has_many :likes

def unfollow(user)
  followerable_relationships.where(followable_id: user.id).destroy_all
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
   # GET /resource/sign_up
   # def new
   #   super
   # end

   # POST /resource
   # def create
   #   super
   # end

   # GET /resource/edit
   # def edit
   #   super
   # end

   # PUT /resource
   # def update
   #   super
   # end

   # DELETE /resource
   # def destroy
   #   super
   # end

   # GET /resource/cancel
   # Forces the session data which is usually expired after sign
   # in to be expired now. This is useful if the user wants to
   # cancel oauth signing in/up in the middle of the process,
   # removing all OAuth session data.
   # def cancel
   #   super
   # end

   # protected

   # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :bio, :avatar])
    end

   # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :bio, :avatar])
    end

   protected

   def update_resource(resource, params)
     # Require current password if user is trying to change password.
     return super if params["password"]&.present?

     # Allows user to update registration information without password.
     resource.update_without_password(params.except("current_password"))
   end
   # The path used after sign up for inactive accounts.
   # def after_inactive_sign_up_path_for(resource)
   #   super(resource)
   # end
 end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user , except: [:search]
  before_action :authenticate_user!

  def index

  end

  def search
    @users = User.where("email LIKE ?","%" + params[:q] + "%")
  end


  def show
    @user = User.find(params[:id])
    @posts= @user.posts
  end
  def follow

     current_user.send_follow_request_to(@user)
    @user.accept_follow_request_of(current_user)
     redirect_to users_path

   end

   def unfollow

     current_user.unfollow(@user)
    redirect_to users_path

  end

   def accept

    current_user.accept_follow_request_of(@user)
     redirect_to users_path
   end


   def decline
 current_user.decline_follow_request_of(@user)
 redirect_to users_path
  end

   def cancel
    current_user.remove_follow_request_for(@user)
     redirect_to users_path
  end

   def set_user
   @user = User.find(params[:id])
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/mystories.html.erb
<h1>HELLO WORLD</h1>

app/views/users/search.html.erb
<div style="padding: 20px ;display: flex; justify-content: center;" >
<h1 >SEARCH RESULT</h1>
</div>
<%#= render @users %>

<% @users.each do |user|%>
<div style="border: 1px solid; padding: 5px; margin-bottom: 10px;">
 <% if user.avatar.attached?%>
<%= image_tag user.avatar, style:"width: 100px; height: 100px"%>
 <% end%>


<b>
<%= link_to user.username ,user %><br>
<%= user.bio%></b>
<br><br>
</div>
<% end %>

app/views/users/show.html.erb
<div class="row">
<div class="col-12" style="margin-top: 20px ; padding: 20px; background-color: #f6f6f6">

      <div style="position:relative; left:0px">
      <% if @user.avatar.attached?%>
      <%= image_tag @user.avatar, style:"width: 150px; height: 150px"%>
      <% end%>
      </div>

<h1><%#= @user.email%></h1>
<h3><%= @user.username%></h3>
<h5><%= @user.bio%></h5>
<%= button_to "Edit Account" , edit_user_registration_path, method: :get%><br>
<%= button_to "View Story" ,  users_mystories_path , method: :get %><br>

<hr>
<div>
<% if current_user.id == @user.id %>
  Followers
  <% @user.followers.each do |follower| %>
    <p> <b> <%= link_to follower.email, follower %> </b> </p>
  <% end %>

  Following
  <% @user.following.each do |following| %>
    <p> <%= link_to following.email, following %> </p>
  <% end %>
<% end %>
</div>

 <% if current_user.following?(@user) %>
      <%= button_to "Unfollow", unfollow_path(@user)%>
    <% elsif current_user.sent_follow_request_to?(@user) %>
      <%= button_to "Cancel follow request", cancel_path(@user) %>
    <% else %>
      <% if @user.id == current_user.id %>
      <% else %>
        <%= button_to "Follow", follow_path(@user)%>
      <% end %>
    <% end %>

<div id="posts" class="text-center">
<% @posts.each do |post| %>
<% if current_user.id == post.user_id.to_i %>
  <%= render post %>
<% end %>
  <% end %>
</div>


</div>
</div>