config/routes.rb
Rails.application.routes.draw do

  resources :stories
  resources :likes, only: [:create,:destroy]

  resources :comments
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }

  resources :users, only: [:show]

  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"

  get 'search', to:"users#search"
  get 'home/about'
  get 'posts/myposts'
  get 'stories/mystories'

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord

validates :title, presence: true
validates :description, presence: true
validates :keywords, presence: true

has_many_attached :images
belongs_to :user
has_many :comments
has_many :likes
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def myposts
    @posts = Post.all
  end
  # GET /posts/1 or /posts/1.json
  def show
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keywords,:user_id, images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="col-xl-4" style="margin: auto">
<h1>New Post</h1>
<%= form_with(model: post, local: true) do |form| %>


  <% invalid  = post.errors.include?(:title) %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title , class: "form-control" %>
  <% if invalid%>
  <p style= "color:red">
  <%= post.errors.full_messages_for(:title).join(" ,")%>
  </p>
  <% end %>
  </div>

<%= form.text_field :user_id,type: "block", value: current_user.id %>

<% invalid  = post.errors.include?(:description) %>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
 <% if invalid%>
  <p style= "color:red">
  <%= post.errors.full_messages_for(:description).join(" ,")%>
  </p>
  <% end %>
  </div>

<% invalid  = post.errors.include?(:keywords) %>
  <div class="field">
    <%= form.label :keywords %>
    <%= form.text_field :keywords, class: "form-control" %>
    <% if invalid%>
  <p style= "color:red">
  <%= post.errors.full_messages_for(:keywords).join(" ,")%>
  </p>
  <% end %>
  <%= form.file_field :images, multiple: true%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary col-12" %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<%= stylesheet_link_tag("test")%>

<div id="<%=dom_id post%>" class="post-container">

<% post.images.each do |image|%>
 <%= image_tag(image, style: "object-fit: contain; width:400px; height:400px")%>
<% end %>

<div style="margin-top: 10px; margin-bottom: 10px">
<% if user_signed_in?%>
<% like = current_user.likes.find_by(post: post)%>
  <% if like.nil?%>
<%= button_to "like", likes_path, params: { like: {post_id:post.id}}, method: :post%>
<%else %>
<%= button_to "Unlike", like_path(like), method: :delete%>
<%end%>
<%end%>
</div>


<div class="details">

<%#= post.user.username%>
 <% if post.user.avatar.attached?%>
 <%= image_tag post.user.avatar, style:"width: 30px; height: 30px"%>
 <% end%>

<%= link_to post.user.username ,post.user %>
<%= post.title %>
</div>

<%#= post.description%><br>
<%#= post.keywords %>

<p><%#= link_to "" ,post, class:"post-link"%></p>
<p><%= link_to "View Post" ,post %></p>



<p><%= post.likes.count %> Likes </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post")%>
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>

  <% current_user.follow_requests.each do |request| %>
    <%= request.followerable.email %> Wants to follow you
    <%= button_to "Accept", accept_path(request.followerable) %>
    <%= button_to "Decline", decline_path(request.followerable) %>
  <% end %>
  <br>

<h1>Posts</h1>
<div id="posts" class="text-center">
<% @posts.each do |post| %>
  <%= render post %>
  <hr>
  <% end %>
</div>
<br>
<% else%>

<h1 style= "padding: 20px ;margin: 0 auto; text-align: center; ">You must be logged in to view content</h1>
<br>
  <div style="position:relative; left:45%">
  <%= button_to "Click here to Log in", new_user_session_path , class:"nav-link"  %><br />
  </div>
<% end %>

app/views/posts/myposts.html.erb
<%= stylesheet_link_tag("post")%>
<p id="notice"><%= notice %></p>
<h1>Posts</h1>
<div id="posts" class="text-center">

<% @posts.each do |post| %>
<% if current_user.id == post.user_id.to_i %>
  <%= render post %>
<% end %>
  <% end %>
</div>
<br>

app/views/posts/new.html.erb
<div class="row">
<%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', posts_path %>
<%= render @post%>
<% if user_signed_in?%>
<% if current_user.id == @post.user_id.to_i %>

<%= link_to 'Edit', edit_post_path(@post) %> |

<%= button_to 'Delete Post', @post, method: :delete %>

  <% end %>
  <% end %>

<%- @post.comments.each do |comment|%>
<%= comment.text%><br>
  <% end %>


<%= render "comments/form"%>