config/routes.rb
Rails.application.routes.draw do

  resources :stories
  resources :likes, only: [:create,:destroy]

  resources :comments
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }

  resources :users, only: [:show]

  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"

  get 'search', to:"users#search"
  get 'home/about'
  get 'posts/myposts'
  get 'stories/mystories'

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue pt-4">
<div class="abc" style="position: relative; left:0; bottom:0; width: 100%; height: 15%">
<h3>Footer Test</h3>
</div>
</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", root_path, class: "navbar-brand"%>
  <% if user_signed_in?%>
      <% if current_user.avatar.attached?%>
      <%= image_tag current_user.avatar, style:"width: 50px; height: 50px"%>
      <% end%>
         <% end%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Upload Post" , new_post_path, class:"nav-link"%>
      </li>

  <li class="nav-item">
        <%= link_to "Upload Story" , new_story_path, class:"nav-link"%>
      </li>


       <li class="nav-item">
        <%= link_to "About" , home_about_path, class:"nav-link"%>
      </li>
      <% if user_signed_in?%>
         <li class="nav-item">
        <%= link_to "View Profile" , current_user, class:"nav-link"%>
      </li>

      <li class="nav-item">
        <%= link_to "Sign Out" , destroy_user_session_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%#= link_to "Edit Account" , edit_user_registration_path, class:"nav-link"%>
      </li>
       <li class="nav-item">
        <%= link_to "View My Stories" , stories_mystories_path, class:"nav-link"%>
      </li>
      <%else %>
      <li class="nav-item">
        <%= link_to "Sign up" , new_user_registration_path, class:"nav-link"%>
      </li>
      <%end%>

    <form class="form-inline my-2 my-lg-0" action="/search" style="position: relative;left: 800px;  ">
    <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-successs my-2 my-sm-0" type="submit">Search</button>
    </form>


    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar"%>
    <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render "layouts/footer"%>

  </body>
</html>